server:
  port: 9090

spring:
  application:
    name: xrcgs-admin
  # 用 profile 组的方式：激活 dev ≡ 同时激活 dev 和 local
  profiles:
    group:
      dev: [dev, local]
      prod: [prod]
    active: local
  servlet:
    multipart:
      max-file-size: 500MB  # 单个文件
      max-request-size: 1024MB  # 一次请求（多文件总和）
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    com.xrcgs.syslog.mapper: debug


#Actuator确认服务在线设置
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"

jwt:
  # 至少 64 位长度（建议 Base64 随机串，示例仅演示）
  secret: "xrcgs-THIS_IS_A_DEMO_SECRET_PLEASE_REPLACE_WITH_A_RANDOM_64+_CHARS_STRING_2025_xrcgs_xrcgs_xrcgs"
  issuer: "xrcgs"
  access-ttl-seconds: 28800       # 8h
  refresh-ttl-seconds: 604800    # 7d
  header: "Authorization"
  prefix: "Bearer "